---
channel: edge
addons:
  cloudflared:
    repository: homeassistant-apps/app-cloudflared
    target: cloudflared
    image: ghcr.io/homeassistant-apps/cloudflared/{arch}
  newt:
    repository: homeassistant-apps/app-newt
    target: newt
    image: ghcr.io/homeassistant-apps/newt/{arch}
  code-server:
    repository: homeassistant-apps/app-code-server
    target: code-server
    image: ghcr.io/homeassistant-apps/code-server/{arch}
